### ISSUE TITLE
Changing button text when accordion is open

### ISSUE THREAD

**Issue by jerauf** [vctrfrnndz/jquery-accordion#9]
How do you change the button text when the accordion is open? I want it to say "get more info" when it's closed and "less info" when it's open.

**Comment by gpassarelli** [comment]
@jerauf I did this using only the css classes;

# TL;DR
When the accordion is opened, it adds the class `.open` to the  `data-accordion` element.

My code look like this:
```php

<div class="accordion" data-accordion>
    <div class="accordion__title accordion__title--closed" data-control>
        {!! $closed_title !!}
    </div>
    <div class="accordion__title accordion__title--opened" data-control>
        {!! $opened_title !!}
    </div>
    <div class="accordion__content">
        {!! $accordion['content']  !!}
    </div>
</div>
```

And my css is like this:
```scss
.accordion {
  .accordion__title {
    position: relative;
    display: inline-block;
    &:hover {
      cursor: pointer;
    }
  }
  .accordion__title--opened {
    display: none;
  }
  &.open {
    .accordion__title--closed {
      display: none;
    }
    .accordion__title--opened {
      display: inline-block;
    }
  }
```
